language: python

python: 
  - 3.6

install:
  - pip install -r requirements.txt

script:
  - python -m pytest tests --cov
  # python -m pytest tests --cov-report term-missing --cov
  
after_success:
  - coveralls
